version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19sskn2wxl0ks"
s3_prefix = "cloud-resume-challenge"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
